# Generated by Django 4.1.1 on 2022-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeManager',
            fields=[
                ('timeID', models.IntegerField(primary_key=True, serialize=False)),
                ('lastModified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
