# Generated by Django 4.1.1 on 2022-11-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_apiiddictionary_fplname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fplapistatsgameweek',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fplapistatsgameweek',
            name='fpl_id',
            field=models.IntegerField(default=0, verbose_name='FPL ID'),
        ),
    ]
