# Generated by Django 4.1.1 on 2022-11-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_fplapistatsgameweek_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='understatapistatsgameweek',
            name='understat_fixtureID',
            field=models.IntegerField(default=0, verbose_name='Gameweek'),
        ),
        migrations.AddField(
            model_name='understatapistatsgameweek',
            name='understat_playerName',
            field=models.CharField(default='', max_length=100, verbose_name='Understat Name'),
            preserve_default=False,
        ),
    ]
