# Generated by Django 4.1.1 on 2022-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_understatapistatsgameweek_understat_fixtureid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='understatapistatsgameweek',
            name='understat_yellow_cards',
        ),
        migrations.AddField(
            model_name='fplapistatsgameweek',
            name='fpl_yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Yellow Cards'),
        ),
    ]
