# Generated by Django 4.1.1 on 2022-12-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_remove_understatapistatsgameweek_understat_yellow_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='understatapistatsgameweek',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='understatapistatsgameweek',
            name='understat_id',
            field=models.IntegerField(default=0, verbose_name='Understat ID'),
        ),
    ]
