# Generated by Django 4.1.1 on 2023-01-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0009_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
