# Generated by Django 4.1.1 on 2023-01-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0010_delete_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leaguePos',
        ),
    ]
