# Generated by Django 4.1.1 on 2023-01-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0012_alter_fixture_gameweeknumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='awayTeamID',
            field=models.IntegerField(verbose_name='Away Team ID'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='homeTeamID',
            field=models.IntegerField(verbose_name='Home Team ID'),
        ),
    ]
