# Generated by Django 4.1.1 on 2023-01-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0013_alter_fixture_awayteamid_alter_fixture_hometeamid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timeManager',
        ),
    ]
