# Generated by Django 4.1.1 on 2023-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0015_playerteamandposition_delete_playerteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamandposition',
            name='xP',
            field=models.FloatField(default=0, verbose_name='Expected Points'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='teamStrength',
            field=models.FloatField(default=0, verbose_name='Team Strength'),
            preserve_default=False,
        ),
    ]
