# Generated by Django 4.1.1 on 2023-01-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0016_playerteamandposition_xp_team_teamstrength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fplapistatsgameweek',
            name='fpl_position',
        ),
        migrations.RemoveField(
            model_name='fplapistatsgameweek',
            name='fpl_team',
        ),
    ]
