# Generated by Django 4.1.1 on 2023-01-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0018_playerteamandposition_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xpgameweek',
            name='playerID',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='awayTeamStrength',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='homeTeamStrength',
        ),
        migrations.DeleteModel(
            name='TeamFixture',
        ),
        migrations.DeleteModel(
            name='XPGameweek',
        ),
    ]
